version: "3.9"

services:
  storage-server:
    image: ${REGISTRY_HOST}/storage-server:latest
    volumes:
    - ./configs:/data/conf
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: storage
        traefik.http.routers.storage.entrypoints: https
        traefik.http.routers.storage.tls: "true"
        traefik.http.routers.storage.tls.certresolver: letsencrypt
        traefik.http.routers.storage.rule: Host(`storage.${SUBDOMAIN}.${DOMAIN}`)
        traefik.http.services.storage.loadbalancer.server.port: 8000
      placement:
        constraints:
          - "node.labels.cluster==swarm"
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
